# version: '1.0.0'

services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  server-auth:
    build: ./Auth
    ports:
      - 3001:3001
    volumes:
      - ./Auth:/app
      - /app/node_modules
    env_file:
      - ./Auth/config/.env
    depends_on:
      - mongodb

  server-upload:
    build: ./Video
    ports:
      - 3002:3002
    volumes:
      - ./Video:/app
      - /app/node_modules
    env_file:
      - ./Video/config/.env
    depends_on:
      - mongodb

      
  data-server:
    build: ./Data
    ports:
      - 3003:3003
    volumes:
      - ./Data:/app
      - /app/node_modules
    env_file:
      - ./Data/config/.env
    depends_on:
      - mongodb


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:secret@mongodb:27017/

volumes:
  data:
